# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

strategy:
  matrix:
      imageName: 'windows-latest'
      nodeVersion: '8.x'
    windows-node10:
      imageName: 'windows-latest'
      nodeVersion: '10.x'

pool:
  vmImage: $(imageName)

trigger:
  branches:
    include:
      - master
      - greenkeeper/*
pr:
  - master

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(nodeVersion)
    displayName: 'Install Node.js'

  - script: npm install
    displayName: 'Install dependencies'

  - script: npm run getenv:esetget
    displayName: 'echo variable'

  - script: npm run getenv:echodef
    displayName: 'echo default variable'

  - script: npm run getenv:echoset
    displayName: 'echo set variable'

  - script: npm run getenv:copy
    displayName: 'copy env file'
# TODO: manage login to @azure/ng-deploy and az cli before enabling
#- script: bash -c "bash -c \"scripts/test.sh\""
#  displayName: 'Run e2e tests'
